name: Publish Release

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Get Tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release
          tag: ${{ steps.vars.outputs.tag }}
